version: '3'
services:
  console:
    image: cjoakim/cosmosdb-gremlin-bulkloader:latest
    environment:
    - AZURE_COSMOSDB_GRAPHDB_CONN_STRING=${AZURE_COSMOSDB_GRAPHDB_CONN_STRING}
    - AZURE_COSMOSDB_GRAPHDB_DBNAME=${AZURE_COSMOSDB_GRAPHDB_DBNAME}
    - AZURE_COSMOSDB_GRAPHDB_GRAPH=${AZURE_COSMOSDB_GRAPHDB_GRAPH}
    - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    - CLI_ARGS_STRING=load --!verbose --throttle 5 --file-type vertex --blob-container bulkloader --blob-name imdb/loader_movie_vertices.csv
